name: Build Digital Forensic Investigation Tool

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller reportlab Pillow

      - name: Build application
        shell: bash
        run: |
          pyinstaller --onefile --windowed src/Digital_Forensic_Investigation_Tool.py

      - name: Upload Windows EXE
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: dist/*.exe

      - name: Upload Linux Executable
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Binary
          path: dist/*

      - name: Upload macOS App
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/*.app

      - name: Build macOS App
        if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -rf dist build
          pyinstaller --windowed -y src/Digital_Forensic_Investigation_Tool.py

      - name: Install create-dmg
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install create-dmg

      - name: Create DMG
        if: runner.os == 'macOS'
        shell: bash
        run: |
          create-dmg \
            "Digital_Forensic_Investigation_Tool.dmg" \
            "dist/Digital_Forensic_Investigation_Tool.app"

      - name: Upload macOS DMG
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG
          path: Digital_Forensic_Investigation_Tool.dmg